### ISSUE TITLE
Puma error on localhost:3000

### ISSUE THREAD

**Issue by chowyb** [nusskylab/nusskylab#573]
Hi,

I seem to be having issues when accessing localhost:3000 after setting up a vagrant instance. At this point, I am attempting to complete step 4 of the [preparation stage](https://github.com/nusskylab/nusskylab/wiki/Developing-NUSSkylab-with-Vagrant#preparation). When accessing the page, the following error log is displayed:

```
Puma caught this error: Missing `secret_token` and `secret_key_base` for 'development' environment, set these values in `config/secrets.yml` (RuntimeError)
/home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.2/lib/rails/application.rb:534:in `validate_secret_key_config!'
/home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.2/lib/rails/application.rb:246:in `env_config'
/home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.2/lib/rails/engine.rb:514:in `call'
/home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.2/lib/rails/application.rb:164:in `call'
/home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
/home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/puma-2.11.3/lib/puma/server.rb:507:in `handle_request'
/home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/puma-2.11.3/lib/puma/server.rb:375:in `process_client'
/home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/puma-2.11.3/lib/puma/server.rb:262:in `block in run'
/home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/puma-2.11.3/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

I also note that I had encountered issues with Devise.secret_key not being set (similar to #568), which I may have incorrectly attempted to fix by copying the config.secret_key from the terminal directly into the devise.rb initializer.

**Comment by chowyb** [comment]
Fixed; had to update the values in `/config/secrets.yml` as well.
